from __future__ import annotations

import math

import numpy as np

from flow_tte.darc_geometry import (
    FeatureGrid,
    ImageSize,
    Point2D,
    PointPairs,
    RealizedResize,
    SimilarityRansacConfig,
    fit_similarity_ransac,
    mutual_nearest_pairs,
    token_centers,
)


def test_half_pixel_resize_round_trips_native_points() -> None:
    # Given: a non-uniform realized resize followed by a right/bottom patch crop.
    resize = RealizedResize(
        native=ImageSize(height=100, width=200),
        realized=ImageSize(height=200, width=300),
        retained=ImageSize(height=192, width=288),
    )
    native = Point2D(x=19.0, y=9.0)

    # When: the native pixel center is mapped forward and back.
    resized = resize.native_to_resized(native)
    restored = resize.resized_to_native(resized)

    # Then: the frozen half-pixel equation is exact up to floating-point precision.
    assert math.isclose(resized.x, 28.75)
    assert math.isclose(resized.y, 18.5)
    assert math.isclose(restored.x, native.x)
    assert math.isclose(restored.y, native.y)


def test_retained_region_excludes_right_bottom_patch_remainder() -> None:
    # Given: a realized resize with a cropped right/bottom remainder.
    resize = RealizedResize(
        native=ImageSize(height=100, width=200),
        realized=ImageSize(height=200, width=300),
        retained=ImageSize(height=192, width=288),
    )
    inside = resize.resized_to_native(Point2D(x=287.49, y=191.49))
    outside = resize.resized_to_native(Point2D(x=287.5, y=191.5))

    # When: native points are checked against the retained resized footprint.
    inside_result = resize.contains_retained_native(inside)
    outside_result = resize.contains_retained_native(outside)

    # Then: the upper half-pixel boundary is exclusive.
    assert inside_result
    assert not outside_result


def test_token_centers_use_patch_half_pixel_coordinates() -> None:
    # Given: a two-row, three-column patch grid.
    shape = ImageSize(height=2, width=3)

    # When: patch-16 token centers are enumerated in row-major order.
    centers = token_centers(shape)

    # Then: centers follow 16 * (index + 0.5) - 0.5.
    expected = np.asarray(
        [[7.5, 7.5], [23.5, 7.5], [39.5, 7.5], [7.5, 23.5], [23.5, 23.5], [39.5, 23.5]],
        dtype=np.float32,
    )
    assert np.array_equal(centers, expected)


def test_mutual_nearest_pairs_remove_one_way_feature_matches() -> None:
    # Given: one support is a query nearest neighbour without being mutual.
    centers = token_centers(ImageSize(height=1, width=3))
    support = FeatureGrid(
        features=np.asarray([[1.0, 0.0], [0.0, 1.0], [0.8, 0.2]], dtype=np.float32),
        centers=centers,
    )
    query = FeatureGrid(
        features=np.asarray([[1.0, 0.0], [0.0, 1.0]], dtype=np.float32),
        centers=centers[:2],
    )

    # When: cosine nearest neighbours are intersected in both directions.
    pairs = mutual_nearest_pairs(support, query)

    # Then: only the two reciprocal matches remain.
    assert np.array_equal(pairs.support_points, centers[:2])
    assert np.array_equal(pairs.query_points, centers[:2])


def test_similarity_ransac_recovers_orientation_preserving_transform() -> None:
    # Given: sixteen exact inliers, four outliers, and a known 4-DOF similarity.
    support = np.asarray(
        [(float(x), float(y)) for y in range(4) for x in range(4)],
        dtype=np.float32,
    )
    theta = math.radians(12.0)
    scale = 1.1
    linear = scale * np.asarray(
        [[math.cos(theta), -math.sin(theta)], [math.sin(theta), math.cos(theta)]],
        dtype=np.float32,
    )
    query = support @ linear.T + np.asarray([12.0, -7.0], dtype=np.float32)
    support_all = np.concatenate((support, np.asarray([[50.0, 50.0]] * 4, dtype=np.float32)))
    query_all = np.concatenate((query, np.asarray([[-50.0, 70.0]] * 4, dtype=np.float32)))
    pairs = PointPairs(support_points=support_all, query_points=query_all)
    config = SimilarityRansacConfig(reprojection_threshold=0.05, max_median_error=0.04)

    # When: the preregistered partial-affine RANSAC is fitted.
    result = fit_similarity_ransac(pairs, config=config, seed=17)

    # Then: it accepts the correct orientation-preserving transform.
    assert result.accepted
    assert result.inlier_count == 16
    assert math.isclose(result.scale, scale, rel_tol=1e-5)
    assert np.allclose(result.matrix[:, :2], linear, atol=1e-5)
    assert np.allclose(result.matrix[:, 2], [12.0, -7.0], atol=1e-5)
    assert np.linalg.det(result.matrix[:, :2]) > 0.0


def test_similarity_ransac_rejects_reflection() -> None:
    # Given: correspondences generated by a reflection, not a rotation.
    support = np.asarray(
        [(float(x), float(y)) for y in range(4) for x in range(4)],
        dtype=np.float32,
    )
    query = support @ np.asarray([[-1.0, 0.0], [0.0, 1.0]], dtype=np.float32).T
    pairs = PointPairs(support_points=support, query_points=query)
    config = SimilarityRansacConfig(reprojection_threshold=0.01, max_median_error=0.01)

    # When: an orientation-preserving similarity is fitted.
    result = fit_similarity_ransac(pairs, config=config, seed=23)

    # Then: the reflected geometry cannot pass the frozen acceptance checks.
    assert not result.accepted


def test_similarity_ransac_rejects_out_of_range_scale() -> None:
    # Given: a perfectly fitted transform above the frozen maximum scale.
    support = np.asarray(
        [(float(x), float(y)) for y in range(4) for x in range(4)],
        dtype=np.float32,
    )
    query = support * 1.3 + np.asarray([4.0, 8.0], dtype=np.float32)
    pairs = PointPairs(support_points=support, query_points=query)
    config = SimilarityRansacConfig(reprojection_threshold=0.01, max_median_error=0.01)

    # When: the similarity is fitted accurately.
    result = fit_similarity_ransac(pairs, config=config, seed=29)

    # Then: acceptance rejects scale outside [0.8, 1.25].
    assert math.isclose(result.scale, 1.3, rel_tol=1e-5)
    assert not result.accepted
